# Import necessary libraries

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
import pickle 
fileObj = open('model.obj', 'wb')

# Load the BMI dataset

In [11]:
data = pd.read_csv('bmi.csv')

# Convert Gender to binary (1 for Male, 0 for Female)

In [12]:
data = pd.get_dummies(data, columns=['Gender'], drop_first=True, dtype=int)

# Define features and target variable

In [13]:
X = data.drop('Index', axis=1)
y = data['Index']

# Split the data into training and testing sets

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Train the Logistic Regression model with L2 regularization

In [15]:
log_model = LogisticRegression(penalty='l2', solver='lbfgs', multi_class='multinomial', max_iter=10000)
log_model.fit(X_train, y_train)

#save the model
pickle.dump(log_model,fileObj)
fileObj.close()

/Users/iamjcoo/miniforge3/envs/tensorflow-env/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Evaluate the Logistic Regression model

In [16]:
#retrieving the model using pickle
fileObj = open('model.obj', 'rb')
model = pickle.load(fileObj)

preds = model.predict(X_test)
accuracy = accuracy_score(y_test, preds)
print("Logistic Regression Model Accuracy: {:.2f}%".format(accuracy * 100))

Logistic Regression Model Accuracy: 94.67%


# Evaluate the Logistic Regression model with confusion matrix and classification report

In [17]:
print("\nConfusion Matrix:\n", confusion_matrix(y_test, preds))
print("\nClassification Report:\n", classification_report(y_test, preds))


Confusion Matrix:
 [[ 1  0  0  0  0  0]
 [ 1  5  0  0  0  0]
 [ 0  0 22  1  0  0]
 [ 0  0  2 17  0  0]
 [ 0  0  0  2 35  1]
 [ 0  0  0  0  1 62]]

Classification Report:
               precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.83      0.91         6
           2       0.92      0.96      0.94        23
           3       0.85      0.89      0.87        19
           4       0.97      0.92      0.95        38
           5       0.98      0.98      0.98        63

    accuracy                           0.95       150
   macro avg       0.87      0.93      0.89       150
weighted avg       0.95      0.95      0.95       150

